# Generated by Django 5.1.4 on 2024-12-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('prize', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
